[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"  # Явно включаем плагин

[[plugins]]
  package = "@netlify/plugin-nextjs"
  # Указываем версию плагина для гарантии совместимости
  version = "5.11.6"
